version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.4-stretch-node
    working_directory: ~/calva
    steps:
      - checkout:
          path: ~/calva
      - restore_cache: 
          name: Restore node-modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node_modules
          command: npm install
      - save_cache:
          name: Save node-modules
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Compile and Run Tests
          command: npm run compile-cljs 
  build:
    docker:
      - image: circleci/openjdk:11.0.4-stretch-node
    working_directory: ~/calva
    steps:
      - checkout:
          path: ~/calva
      - restore_cache: 
          name: Restore node-modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node_modules
          command: npm install
      - save_cache:
          name: Save node-modules
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install vsce
          command: sudo npm install -g vsce
      - run:
          name: package vsix
          command: vsce package
      - run:
          name: Copy vsix
          command: |
            mkdir /tmp/artifacts
            cp *.vsix /tmp/artifacts/
      - store_artifacts:
           path: /tmp/artifacts
      - run:
          name: Save version to file
          command: node -p 'require("./package.json").version' > /tmp/artifacts/version
      - persist_to_workspace:
           root: /tmp
           paths:
              - artifacts
  publish:
    docker:
      - image: circleci/openjdk:11.0.4-stretch-node
    steps:
      - attach_workspace:
         at: /tmp
      - run:
          name: Install vsce
          command: sudo npm install -g vsce
      - run:
          name: Set Version variable
          command: export CALVA_VERSION=$(cat /tmp/artifacts/version)
      - run:
          name: Publish to the marketplace
          command: vsce publish --packagePath /tmp/artifacts/calva-$CALVA_VERSION.vsix -p $PUBLISH_TOKEN
workflows:
  version: 2
  build_publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish-approval:
          requires:
            - build
          filters:  
                branches:
                  only:
                    - release
          type: approval
      - publish:
          requires:
            - publish-approval
          context: Calva
          