version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.4-stretch-node
    working_directory: ~/calva
    steps:
      - checkout:
          path: ~/calva
      - restore_cache: 
          name: Restore dependencies
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node_modules
          command: npm install
      - run:
          name: Compile and Run Tests
          command: npm run compile-cljs 
      - save_cache:
          name: Save dependencies
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.m2
  build:
    docker:
      - image: circleci/openjdk:11.0.4-stretch-node
    working_directory: ~/calva
    steps:
      - checkout:
          path: ~/calva
      - restore_cache: 
          name: Restore dependencies
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Tamper Calva version if not release
          command: test "release" = "${CIRCLE_BRANCH}" && echo 'No version tampering on release branch' || npx json -I -f package.json -e 'this.version=this.version.replace(/$/, "-'${CIRCLE_SHA1:0:8}'")'
      - run:
          name: package vsix
          command: npx vsce package
      - run:
          name: Copy vsix
          command: |
            mkdir /tmp/artifacts
            cp *.vsix /tmp/artifacts/
      - store_artifacts:
           path: /tmp/artifacts
      - persist_to_workspace:
           root: /tmp
           paths:
              - artifacts
  publish:
    docker:
      - image: circleci/openjdk:11.0.4-stretch-node
    working_directory: ~/calva
    steps:
      - attach_workspace:
         at: /tmp
      - checkout:
          path: ~/calva
      - restore_cache: 
          name: Restore dependencies
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Publish to the marketplace
          command: npx vsce publish --packagePath /tmp/artifacts/calva-$(node -p 'require("./package.json").version').vsix -p ${PUBLISH_TOKEN}
workflows:
  version: 2
  build_publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish-approval:
          requires:
            - build
          filters:  
                branches:
                  only:
                    - release
          type: approval
      - publish:
          requires:
            - publish-approval
          context: Calva
          